# Generated by Django 5.0.1 on 2024-01-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0002_rename_name_book_book_name_remove_book_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
